// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sqylcbwqmospzzmohtor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeWxjYndxbW9zcHp6bW9odG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTg4NDksImV4cCI6MjA3MzczNDg0OX0.5DNoerhwqCpSJKLTSvh1imqUOdzV8olVoM6bF22RXOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);